### PR TITLE
wrote test for sellOption function

### PR DESCRIPTION
**Pull request by jerrynoah96**
Wrote test for sellOption function. Included two test tokens that will be used as underlying tokens in test.
wrote a function in optionsmarket.sol to setDai Address for ease of testing. Also added the "public" keyword where lastOrderId and lastPurchaseId is declared so they can be accessible as a function

### CODE REVIEW

**Comment by uwe** [comment]
Please add `node_modules` to `.gitignore`.

**Comment by avoyager** [comment]
@uwe I mentioned this as well. Once the bulk of extra files are removed we can merge. Also, there is a small issue with the tests that I believe @jerrynoah96 is submitting in the next pull request.

**Comment by uwe** [comment]
@jerrynoah96 you also need to remove them from version control: `git rm -rf node_modules` and then run `npm install` again.

**Comment by jerrynoah96** [comment]
@uwe  perfect now?

**Comment by uwe** [comment]
@jerrynoah96 I'm not the gatekeeper for this repo. I do not have commit rights.

I think the following could be improved:
- remove (and gitignore) `build/contracts`
- make tests run via `npm run` (not a long list of manual steps)
- put test artefacts (`dai.sol`) somewhere else (maybe in `test` folder), maybe `ABI` as well

Look at the sister repo https://github.com/YieldHand/OptionsMarketLiquidityPool, the tests are easily runnable there.

**Comment by jerrynoah96** [comment]
@uwe  thanks, looking into it already

**Comment by jerrynoah96** [comment]
@uwe i have made the necessary changes , will update now..

for the test, truffle develop then test, should work fine. but the first 2 steps had to be there because the dai address on maiinnet had been hardcoded in the contract hence the reason for the list

but really, in the list, there are just 3 instructions

- in optionsmarket.sol, comment out line 17 and uncomment line 18 where we have daiTokenAddress;
- un-comment the setDaiAddress function on line 68
then run truffle develop then test

**Pull request closed without merging**
